name: msu_wd_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - selenium==4.29.0
  - webdriver-manager
  - beautifulsoup4
  - spacy
  - pip:
      -  https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0.tar.gz
      -  urllib3
  
